name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run this workflow only when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Get the latest code from GitHub repo
        uses: actions/checkout@v3

      - name: Set up Node.js  # Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies  # Install project dependencies
        run: npm install

      - name: Run tests  # Run your Node.js tests
        run: npm test

      - name: Log in to DockerHub  # Use your secrets to login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}  # Uses the USERNAME secret
          password: ${{ secrets.PASSWORD }}  # Uses the PASSWORD secret

      - name: Build Docker image  # Build Docker image with tag
        run: |
          docker build -t ${{ secrets.USERNAME }}/nodejs-demo-app:latest .

      - name: Push Docker image  # Push the image to DockerHub
        run: |
          docker push ${{ secrets.USERNAME }}/nodejs-demo-app:latest
